email:
    host: smtp.host.com
    port: 465
    user: user@host.com
    password: your_password

server:
    port: 3005

tls:
    enable: false
    key: xx.key
    cert: xx.pem

auth:
    key: secretKeyxxx